### ISSUE TITLE
Does Almalinux consider setting up container sig?

### ISSUE THREAD

**Issue by hjimmy** [AlmaLinux/docker-images#1]
Almalinux is very great, and it is one of the fastest systems to promote the replacement of centos-8, but it seems that it is not perfect at present. I am a community enthusiast and have been engaged in the work related to cloud Native for many years. If Almalinux considers me to participate in the establishment of container SIG, I can provide some help.

**Comment by ezamriy** [comment]
We are definitely going to make a community-driven distribution. As a developer and technical things manager, I can say that any contribution is welcome and that's why I'm uploading things to GitHub under OpenSource licenses.

As for SIGs, our community manager started his work this week and I hope he will introduce himself soon and start coordinating such processes. I shared this question with him.

**Comment by hjimmy** [comment]
Great. Has the almalinux community established a communication channel to communicate the progress of the project? Like Rocketchat or Mattermost channel, can we participate in it?

**Comment by ezamriy** [comment]
@jaboutboul (our community manager) is working on such things.
Nowadays we have the following communication channels:

- https://almalinux.discourse.group/ forum
- `#almalinux` IRC channel on Freenode
- https://www.reddit.com/r/AlmaLinux/

**Comment by jaboutboul** [comment]
hi @hjimmy we would love to have you join the community. You can join us on https://chat.almalinux.org/almalinux/channels/sigcloud. We have lots going on.

**Comment by ezamriy** [comment]
All related information is listed here https://wiki.almalinux.org/sigs/Cloud.html, so I'm closing this issue.
